kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "flask-sample-app-pipeline"
spec:
  serviceAccount: builder
  source:
    git:
        uri: https://github.com/cheers4asc/flaskdemo
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
