apiVersion: psmdb.percona.com/v1-4-0
kind: PerconaServerMongoDB
metadata:
  name: my-cluster-name
spec:
  image: 'percona/percona-server-mongodb-operator:1.4.0-mongod4.2'
  imagePullPolicy: Always
  allowUnsafeConfigurations: false
  secrets:
    users: my-cluster-name-secrets
  pmm:
    enabled: false
    image: 'percona/percona-server-mongodb-operator:1.4.0-pmm'
    serverHost: monitoring-service
  replsets:
    - name: rs0
      size: 3
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      podDisruptionBudget:
        maxUnavailable: 1
      expose:
        enabled: false
        exposeType: LoadBalancer
      arbiter:
        enabled: false
        size: 1
        affinity:
          antiAffinityTopologyKey: kubernetes.io/hostname
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi
  mongod:
    net:
      port: 27017
      hostPort: 0
    security:
      redactClientLogData: false
      enableEncryption: true
      encryptionKeySecret: my-cluster-name-mongodb-encryption-key
      encryptionCipherMode: AES256-CBC
    setParameter:
      ttlMonitorSleepSecs: 60
      wiredTigerConcurrentReadTransactions: 128
      wiredTigerConcurrentWriteTransactions: 128
    storage:
      engine: wiredTiger
      inMemory:
        engineConfig:
          inMemorySizeRatio: 0.9
      mmapv1:
        nsSize: 16
        smallfiles: false
      wiredTiger:
        engineConfig:
          cacheSizeRatio: 0.5
          directoryForIndexes: false
          journalCompressor: snappy
        collectionConfig:
          blockCompressor: snappy
        indexConfig:
          prefixCompression: true
    operationProfiling:
      mode: slowOp
      slowOpThresholdMs: 100
      rateLimit: 100
  backup:
    enabled: false
    restartOnFailure: true
    image: 'percona/percona-server-mongodb-operator:1.4.0-backup'
    serviceAccountName: percona-server-mongodb-operator
